### ISSUE TITLE
no aarch64 and armv7l releases

### ISSUE THREAD

**Issue by bdenckla-ua** [boxboat/fixuid#16]
Any interest in adding releases for these architectures? If not I guess I can just build them for myself.

**Comment by gesquive** [comment]
using goreleaser (https://goreleaser.com/) with travis-ci would be a simple way to get this done. I can start PR if you want.

**Comment by caleblloyd** [comment]
sure, if you'd like those architectures released, we'll accept a PR for it!

**Comment by caleblloyd** [comment]
We now release `linux-arm64`, if you have a downstream project that depends on another arch please drop the link to the project and the needed arch, and we can add
